apiVersion: v1
kind: Namespace
metadata:
  name: dev-drone-hello-functional-test 
  labels:
    environment: dev
    workspace: kaizen-app-team
    workload: hello
    deploymentTarget: hello-functional-test
    someLabel: some-value
