---
# Source: hello-world/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: test
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# Source: hello-world/templates/deployment.yaml
apiVersion: apps/v1
kind: Deploymentncasncja
metadata:
  name: hello-world-deployment
  namespace: test
  annotations:
    version: 0.0.1-23
spec:
  strategy: 
    type: Recreate      
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world      
      annotations:
        version: 0.0.1-23
    spec:
      containers:
      - name: hello-world
        image: ghcr.io/kaizentm/kalypso-app-src/hello-world:0.0.1-23
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: CLUSTER_NAME
          value: cluster
        - name: REGION
          value: westus
        - name: ENVIRONMENT
          value: dev
        - name: DATABASE_URL
          value: https://google.com
