apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: dev.kaizen-app-team..hello-world-app-functional-test.drone
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/kaizentm/kalypso-app-gitops
  ref:
    branch: dev
  secretRef:
      name: repo-secret    
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev.kaizen-app-team..hello-world-app-functional-test.drone
  namespace: flux-system
spec:
  interval: 30s
  targetNamespace: dev-drone-hello-world-app-functional-test
  sourceRef:
    kind: GitRepository
    name: dev.kaizen-app-team..hello-world-app-functional-test.drone
  path: ./functional-test 
  suspend: false
  prune: true

  
