apiVersion: v1
kind: Namespace
metadata:
  name: dev-command-center-hello-functional-test 
  labels:
    environment: dev
    workspace: kaizentm
    workload: hello
    deploymentTarget: hello-functional-test
    someLabel: some-value
