apiVersion: v1
data:
  CLUSTER_NAME: Command Center
  DATABASE_URL: mysql://restricted-host:3306/mysqlrty123
  ENVIRONMENT: Dev
  REGION: East US
  SOME_COMMON_ENVIRONMENT_VARIABLE: "true"
kind: ConfigMap
metadata:
  name: platform-config
  namespace: dev-command-center-hello-functional-test
