apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-app-performance-test
  namespace: argocd
spec:
    destination:
        namespace: dev-kaizen-app-team-hello-world-app-performance-test
        server: https://kubernetes.default.svc              
    project: default
    source:
        path: ./performance-test
        repoURL: https://github.com/eedorenko/kalypso-oci-app-gitops
        targetRevision: dev
        directory:
            recurse: true
            include: '*.yaml'
            exclude: 'kustomization.yaml'
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
        syncOptions:
        - CreateNamespace=true
