apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: rs-dispatcher-framework-1-1-135-t2-msu
spec:
  workload:
    name: rs-dispatcher-framework
    source:
        repo: https://github.com/GM-SDV/rs-dispatcher-framework
        branch: main
        path: .
    application:
        name: ucp
        workspace:
            name: GM-SDV
  deploymentTarget:
    name: msu
    environment: t2
    manifests:
        repo: https://github.com/GM-SDV/rs-dispatcher-framework-gitops
        branch: t2
        path: msu
  workloadVersion:
    version: 1.1.135
    build: build-125
    commit: c569739da7e164d3f127f210b03f2facc2d8a6b
    buildTime: "2023-07-25T23:25:05Z"