apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: rs-dispatcher-framework-1-1-139-d4-msu
  
spec:
  workload:
    name: rs-dispatcher-framework
    source:
        repo: https://github.com/GM-SDV/rs-dispatcher-framework
        branch: main
        path: .
    application:
        name: ucp
        workspace:
            name: GM-SDV
  deploymentTarget:
    name: msu
    environment: d4
    manifests:
        repo: https://github.com/GM-SDV/rs-dispatcher-framework-gitops
        branch: d4
        path: msu
  workloadVersion:
    version: 1.1.139
    build: build-127
    commit: 768973d9da7e164d3f127f210b03f2facc2d8a6b
    buildTime: "2023-07-27T23:25:05Z"