apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: rs-srm-1-1-115-t2-ssu
spec:
  workload:
    name: rs-srm
    source:
        repo: https://github.com/GM-SDV/rs-srm
        branch: main
        path: .
    application:
        name: ucp
        workspace:
            name: GM-SDV
  deploymentTarget:
    name: ssu
    environment: t2
    manifests:
        repo: https://github.com/GM-SDV/rs-srm-gitops
        branch: t2
        path: ssu
  workloadVersion:
    version: 1.1.115
    build: build-95
    commit: 443863d9da7e164d3f127f210b03f2facc2d8a6b
    buildTime: "2023-07-21T23:25:05Z"