name: checkpromote

on:
  push:
    branches:
      - dev

jobs:
  check:
    runs-on: ubuntu-latest    
    steps: 
    - name: Checkout Gitops
      uses: actions/checkout@v3
    - name: Get Promoted Label
      run: |
        pr=$(gh pr list --search $COMMIT_ID --state merged --label promoted)
        echo $pr
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_ID: ${{ github.sha }}

    - name: Wait for deployment to complete   
      run: |
          echo "Waiting..."

  # promote:
  #   needs: check
  #   uses: ./.github/workflows/transform.yaml
  #   with:
  #     promoted_commit_id: ${{ inputs.promoted_commit_id }}
  #     environment: ${{ inputs.promote_environment }}

