name: checkpromote

on:
  push:
    branches:
      - dev

jobs:
  check:
    runs-on: ubuntu-latest
    evironment: ${{ inputs.environment }} 
    steps: 
    - name: Get Promoted Label
      run: |
        pr=$(gh pr list --search "<SHA>" --state merged --label promoted)
        echo $pr

    - name: Wait for deployment to complete   
      run: |
          echo "Waiting..."

  # promote:
  #   needs: check
  #   uses: ./.github/workflows/transform.yaml
  #   with:
  #     promoted_commit_id: ${{ inputs.promoted_commit_id }}
  #     environment: ${{ inputs.promote_environment }}

